### ISSUE TITLE
ExactMatch trigger panic

### ISSUE THREAD

**Issue by ipsusila** [vcaesar/cedar#1]
- Cedar version (or commit ref): v0.20.0
- Go version: 1.18

- Operating system and bit: macOS Catalina 64-bit
- Can you reproduce the bug at [Examples](https://github.com/vcaesar/cedar/tree/master/examples):
  - [ ] Yes (provide example code)
  - [x] No
  - [ ] Not relevant
- Provide example code: 
    ```Go
    d := cedar.New()
    d.Insert([]byte("CEMPAGA"), 1)

    d.ExactMatch([]byte("CEMPAGA"))
    ```
## Description

The above code trigger panic at `fn.go` file, `line 90`.  Output stacktrace:

```
panic: runtime error: index out of range [-2]

goroutine 1 [running]:
github.com/vcaesar/cedar.(*Cedar).Find(0xc000114f41?, {0xc000114f3a?, 0x100?, 0x1?}, 0x1?)
	/Users/ips/Workspace/me/cedar/fn.go:90 +0x1ba
github.com/vcaesar/cedar.(*Cedar).ExactMatch(0xc000136000?, {0xc000114f3a?, 0x0?, 0xc0000021a0?})
	/Users/ips/Workspace/me/cedar/fn.go:197 +0x25
main.main()
	/Users/ips/Workspace/me/cedar/examples/main.go:14 +0x78
exit status 2
```

**Comment by vcaesar** [comment]
Ok, I merged and released a new version.
